default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kennyhwu
  password: secret_password

development:
  <<: *default
  database: menu_development

test:
  <<: *default
  database: menu_test

production:
  <<: *default
  database: menu_production
